
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:150 (project)"
    message: |
      The target system is: iOS -  - arm64
      The host system is: Linux - 6.17.0-14-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /home/f-rat/.local/share/swiftly/bin/clang 
      Build flags: -target;arm64-apple-ios16.0;-arch;arm64;-isysroot;/home/f-rat/theos/sdks/iPhoneOS.sdk;-D_XOPEN_SOURCE=600;-D_DARWIN_C_SOURCE;-Wno-macro-redefined
      Id flags:  
      
      The output was:
      1
      /usr/bin/ld: bilinmeyen öykünüm kipi: llvm
      Desteklenen öykünümler: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386pep i386pe
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /home/f-rat/.local/share/swiftly/bin/clang 
      Build flags: -target;arm64-apple-ios16.0;-arch;arm64;-isysroot;/home/f-rat/theos/sdks/iPhoneOS.sdk;-D_XOPEN_SOURCE=600;-D_DARWIN_C_SOURCE;-Wno-macro-redefined
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      clang version 17.0.0 (https://github.com/swiftlang/llvm-project.git 9784760565e8cae0bc0b97bad69aaf498408dc3d)
      Target: x86_64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      clang version 17.0.0 (https://github.com/swiftlang/llvm-project.git 9784760565e8cae0bc0b97bad69aaf498408dc3d)
      Target: x86_64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" matched "(clang version)":
      clang version 17.0.0 (https://github.com/swiftlang/llvm-project.git 9784760565e8cae0bc0b97bad69aaf498408dc3d)
      Target: x86_64-unknown-linux-gnu
      Thread model: posix
      InstalledDir: /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:150 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/f-rat/Masa\u00fcst\u00fc/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB"
      binary: "/home/f-rat/Masa\u00fcst\u00fc/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB"
    cmakeVariables:
      CMAKE_C_FLAGS: "-target arm64-apple-ios16.0 -arch arm64 -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -Wno-macro-redefined"
      CMAKE_C_FLAGS_DEBUG: "-O0 -g"
      CMAKE_EXE_LINKER_FLAGS: "-target arm64-apple-ios16.0 -arch arm64 -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -fuse-ld=/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin/lld"
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_SYSROOT: "/home/f-rat/theos/sdks/iPhoneOS.sdk"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_ea491/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_ea491.dir/build.make CMakeFiles/cmTC_ea491.dir/build
        gmake[1]: Entering directory '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB'
        Building C object CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o
        /home/f-rat/.local/share/swiftly/bin/clang   -target arm64-apple-ios16.0 -arch arm64 -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -Wno-macro-redefined  -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk   -v -Wl,-v -MD -MT CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        clang version 17.0.0 (https://github.com/swiftlang/llvm-project.git 9784760565e8cae0bc0b97bad69aaf498408dc3d)
        Target: arm64-apple-ios16.0
        Thread model: posix
        InstalledDir: /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin
        clang: warning: -Wl,-v: 'linker' input unused [-Wunused-command-line-argument]
         (in-process)
         "/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin/clang-17" -cc1 -triple arm64-apple-ios16.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -funwind-tables=1 -target-sdk-version=16.4 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -target-cpu apple-a7 -target-feature +zcm -target-feature +zcz -target-feature +v8a -target-feature +aes -target-feature +fp-armv8 -target-feature +neon -target-feature +perfmon -target-feature +sha2 -target-abi darwinpcs -debugger-tuning=lldb -fdebug-compilation-dir=/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB -v -fcoverage-compilation-dir=/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB -resource-dir /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17 -dependency-file CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o.d -skip-unused-modulemap-deps -MT CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -sys-header-deps -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -D _XOPEN_SOURCE=600 -D _DARWIN_C_SOURCE -internal-isystem /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/local/include -internal-isystem /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include -internal-externc-isystem /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/Frameworks -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/SubFrameworks -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/Library/Frameworks -Wno-macro-redefined -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fmax-type-align=16 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -x c /usr/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        clang -cc1 version 17.0.0 based upon LLVM 17.0.0 default target x86_64-unknown-linux-gnu
        ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/local/include"
        ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/SubFrameworks"
        ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/Library/Frameworks"
        #include "..." search starts here:
        #include <...> search starts here:
         /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include
         /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include
         /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/Frameworks (framework directory)
        End of search list.
        Linking C static library libcmTC_ea491.a
        /usr/bin/cmake -P CMakeFiles/cmTC_ea491.dir/cmake_clean_target.cmake
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ea491.dir/link.txt --verbose=1
        /usr/bin/ar qc libcmTC_ea491.a CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o
        /home/f-rat/.local/share/swiftly/bin/llvm-ranlib libcmTC_ea491.a
        gmake[1]: Leaving directory '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:182 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include]
          add: [/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include]
        end of search list found
        collapse include dir [/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include] ==> [/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include]
        collapse include dir [/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include] ==> [/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include]
        implicit include dirs: [/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include;/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "/usr/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:150 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_ea491/fast]
        ignore line: [/usr/bin/gmake  -f CMakeFiles/cmTC_ea491.dir/build.make CMakeFiles/cmTC_ea491.dir/build]
        ignore line: [gmake[1]: Entering directory '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB']
        ignore line: [Building C object CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o]
        ignore line: [/home/f-rat/.local/share/swiftly/bin/clang   -target arm64-apple-ios16.0 -arch arm64 -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -Wno-macro-redefined  -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk   -v -Wl -v -MD -MT CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake-3.31/Modules/CMakeCCompilerABI.c]
        ignore line: [clang version 17.0.0 (https://github.com/swiftlang/llvm-project.git 9784760565e8cae0bc0b97bad69aaf498408dc3d)]
        ignore line: [Target: arm64-apple-ios16.0]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin]
        ignore line: [clang: warning: -Wl -v: 'linker' input unused [-Wunused-command-line-argument]]
        ignore line: [ (in-process)]
        ignore line: [ "/home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/bin/clang-17" -cc1 -triple arm64-apple-ios16.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -funwind-tables=1 -target-sdk-version=16.4 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -target-cpu apple-a7 -target-feature +zcm -target-feature +zcz -target-feature +v8a -target-feature +aes -target-feature +fp-armv8 -target-feature +neon -target-feature +perfmon -target-feature +sha2 -target-abi darwinpcs -debugger-tuning=lldb -fdebug-compilation-dir=/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB -v -fcoverage-compilation-dir=/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB -resource-dir /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17 -dependency-file CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o.d -skip-unused-modulemap-deps -MT CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -sys-header-deps -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -isysroot /home/f-rat/theos/sdks/iPhoneOS.sdk -D _XOPEN_SOURCE=600 -D _DARWIN_C_SOURCE -internal-isystem /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/local/include -internal-isystem /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include -internal-externc-isystem /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/Frameworks -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/SubFrameworks -internal-iframework /home/f-rat/theos/sdks/iPhoneOS.sdk/Library/Frameworks -Wno-macro-redefined -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fmax-type-align=16 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o -x c /usr/share/cmake-3.31/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 17.0.0 based upon LLVM 17.0.0 default target x86_64-unknown-linux-gnu]
        ignore line: [ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/usr/local/include"]
        ignore line: [ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/SubFrameworks"]
        ignore line: [ignoring nonexistent directory "/home/f-rat/theos/sdks/iPhoneOS.sdk/Library/Frameworks"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /home/f-rat/.local/share/swiftly/toolchains/6.2.3/usr/lib/clang/17/include]
        ignore line: [ /home/f-rat/theos/sdks/iPhoneOS.sdk/usr/include]
        ignore line: [ /home/f-rat/theos/sdks/iPhoneOS.sdk/System/Library/Frameworks (framework directory)]
        ignore line: [End of search list.]
        ignore line: [Linking C static library libcmTC_ea491.a]
        ignore line: [/usr/bin/cmake -P CMakeFiles/cmTC_ea491.dir/cmake_clean_target.cmake]
        ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ea491.dir/link.txt --verbose=1]
        ignore line: [/usr/bin/ar qc libcmTC_ea491.a CMakeFiles/cmTC_ea491.dir/CMakeCCompilerABI.c.o]
        ignore line: [/home/f-rat/.local/share/swiftly/bin/llvm-ranlib libcmTC_ea491.a]
        ignore line: [gmake[1]: Leaving directory '/home/f-rat/Masaüstü/projemm/projemm/bin/box64/build_ios/CMakeFiles/CMakeScratch/TryCompile-OAzHjB']
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
